{
    "values": "",
    "others": [
        "",
        "2020-2021Année académique :",
        "Principles of Accounting I38.891ACCT 112EC * ",
        "Mathématiques de l'Informatique311.401AMAT 111  ",
        "Méthodes d'Étude Et De Recherche211.001EDRM 113  * ",
        "General English317.201ENGL 115  * ",
        "Microcomputer Applications317.901INSY 116  * ",
        "Introduction à l étude de la Bible211.201RELB 116  * ",
        "Multivariable Calculus & Differential Equations49.002MATH 126EC ",
        "Logic et Circuits fondamentaux313.202MATH 127  ",
        "Introduction to Computer Programming415.502INSY 227  ",
        "Entretien Des Ordinateurs315.802INSY 214  ",
        "Principles of Accounting I313.202ACCT 112  * ",
        "2021-2022Année académique :",
        "Academic English Writing31ENGL 124* ",
        "Système de Gestion de Base  des Données31INSY 217 ",
        "Programmation avec C41INSY 228 ",
        "Computer Networks41INSY 229 ",
        "Theory of Computation31SENG 224 ",
        "Statistiques Descriptive31STAT 122* ",
        "UNIVERSITE  ADVENTISTE D'AFRIQUE CENTRALE",
        "B.P.  2461 KIGALI, RWANDA",
        "RELEVE DE NOTES",
        "23870Ntirenganya Rene PromesseNom",
        "Faculté",
        "No. Matricule",
        "Option",
        "Mineur ",
        "Software EngineeringInformation Technology",
        ":",
        "::",
        ":",
        "SemSigleCoursCr .NoteCodes",
        "ActiveReports Evaluation. Copyright 2002-2005 (c) Data Dynamics, Ltd. All Rights Reserved.",
        "",
        "UNIVERSITE  ADVENTISTE D'AFRIQUE CENTRALE",
        "B.P.  2461 KIGALI, RWANDA",
        "RELEVE DE NOTES",
        "23870Ntirenganya Rene PromesseNom",
        "Faculté",
        "No. Matricule",
        "Option",
        "Mineur ",
        "Software EngineeringInformation Technology",
        ":",
        "::",
        ":",
        "SemSigleCoursCr .NoteCodes",
        "UNOFFICIAL",
        "Répartition des crédits",
        "Cours généraux",
        "Cours d'option",
        "Cours du mineur",
        "Cours transférés",
        "Cours complémentaires",
        ":",
        ":",
        ":",
        ":",
        ":",
        "0",
        "19",
        "27",
        "0",
        "0",
        "At Kigali, on",
        "Mboyo Mukunde Sylvie",
        "13/01/2022",
        "13.62",
        "12.89",
        "Moyennes",
        "Moyenne générale cumulative",
        "Moyenne d'option cumulative",
        ":",
        ":",
        "    : Cours réussi",
        "EC  : Cours échoué",
        "TF  : Cours transféré",
        "W   : Cours retiré",
        "*   : Cours de formation générale",
        "+   : Cours mineur",
        "( ) : Cours qui ne compte pas pour l'obtention de diplôme de Gestion",
        "Semestres",
        "1  : de septembre à fevrier",
        "2  : de mars à juillet",
        "Codes",
        "Conditions de promotion :  La moyenne générale cumulative de 12 / 20 est",
        "requise pour l'obtention du \"Bachellor Degree\".  Les cours transférés et",
        "les cours complémentaires n'interviennent pas dans le calcul des moyennes,",
        "ainsi que tout cours échoué, s'il est repris et réussi.  1 crédit",
        "semestriel équivaut à 1.5 crédit trimestriel.  Le minimum de 132 crédits",
        "semestriels requis pour avoir le Diplôme de Bachelor Degree équivaut à 198",
        "crédits trimestriels.",
        "ActiveReports Evaluation. Copyright 2002-2005 (c) Data Dynamics, Ltd. All Rights Reserved."
    ]
}